spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/employeeDB?createDatabaseIfNotExist=true
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
server:
  port: 8081